### ISSUE TITLE
New activity icon

### ISSUE THREAD

**Issue by zabellemotte** [remotelearner/moodle-mod_questionnaire#472]
It would be great this wonderful plugin to have a new icon for good integration in Moodle 4 :
https://docs.moodle.org/dev/Moodle_4.0_developer_update#Activity_icons

**Comment by rezeau** [comment]
Coucou Zabelle !
What you want is already done, See https://github.com/PoetOS/moodle-mod_questionnaire/pull/408

**Comment by zabellemotte** [comment]
Merci Joseph et bonne continuation avec les projets Moodle !
