### ISSUE TITLE
Error on emailing responses 

### ISSUE THREAD

**Issue by hernan43** [remotelearner/moodle-mod_questionnaire#48]
In Moodle 2.8 when using the questionnaire module and response emailing I get the following error:

```
Notice: Trying to get property of non-object in /var/www/html/engage/releases/20150720122227/learn/lib/moodlelib.php on line 5884
```

Looking into the code the error is happening here in the ```email_to_user``` function in the ```lib/moodlelib.php``` file:

```
if (!empty($CFG->emailonlyfromnoreplyaddress)) {
  $usetrueaddress = false;
  if (empty($replyto) && $from->maildisplay) {
    $replyto = $from->email;
    $replytoname = fullname($from);
  }
}
```

The ```$from``` in this case is a string so the ```maildisplay``` is not there. In the questionnaire module the ```email_to_user``` function is being called from ```response_send_email``` in the ```questionnaire.class.php``` file:

```
$return = true;
$mailaddresses = preg_split('/,|;/', $email);
foreach ($mailaddresses as $email) {
  $userto = new Object();
  $userto->email = $email;
  $userto->mailformat = 1;
  // Dummy userid to keep email_to_user happy in moodle 2.6.
  $userto->id = -10;
  $userfrom = $CFG->noreplyaddress;
  if (email_to_user($userto, $userfrom, $subject, $altbody, $bodyhtml)) {
    $return = $return && true;
  } else {
    $return = false;
  }
}
```

While the email_to_user function does seem to work with strings the function does specify that the ```$from``` argument is ```stdClass $from A {@link $USER} object```. 

Would it be possible to fake the stdClass object for this to keep the error from happening?

**Comment by mchurchward** [comment]
Seems to be an interesting inconsistency with Moodle there... I'm also not
sure that you have the latest version of 2.8 code there.

This is what I have from line 5876 through line 5896:

    if (!empty($CFG->emailonlyfromnoreplyaddress)) {
        $usetrueaddress = false;
        if (empty($replyto) && $from->maildisplay) {
            $replyto = $from->email;
            $replytoname = fullname($from);
        }
    }

    if (is_string($from)) { // So we can pass whatever we want if there is
need.
        $mail->From     = $CFG->noreplyaddress;
        $mail->FromName = $from;
    } else if ($usetrueaddress and $from->maildisplay) {
        $mail->From     = $from->email;
        $mail->FromName = fullname($from);
    } else {
        $mail->From     = $CFG->noreplyaddress;
        $mail->FromName = fullname($from);
        if (empty($replyto)) {
            $tempreplyto[] = array($CFG->noreplyaddress,
get_string('noreplyname'));
        }
    }

You can see that on line 5884, Moodle allows for the $from variable to be a
string. Looks like if you have the $CFG->emailonlyfromnoreplyaddress set to
something, it doesn't check if the $from is a string.

You are only getting a notification by the way. There is no error. I am
assuming the email is still functioning?

mike

Mike Churchward | Chief Product Officer | Remote-Learner.net Inc.
mike@remote-learner.net
1.877.299.1293 x113 | 1.519.772.3910 x113 | 1.540.943.7831 x113
http://remote-learner.net | http://remote-learner.ca |
http://remote-learner.co.uk

**Comment by hernan43** [comment]
The emails do not appear to be working no. Even so that block of code (```if (empty($replyto) && $from->maildisplay)...```) will never work.
