### ISSUE TITLE
External API error

### ISSUE THREAD

**Issue by aspark21** [remotelearner/moodle-mod_questionnaire#502]
Moodle: MOODLE_402_STABLE
Questionnaire: MOODLE_400_STABLE

Visit your.moodle.site/admin/webservice/documentation.php

<img width="1367" alt="Screenshot 2023-08-01 at 16 40 25" src="https://github.com/PoetOS/moodle-mod_questionnaire/assets/4015496/92ac380e-fdf9-4225-9d88-479272f60915">

**Comment by mchurchward** [comment]
I can't replicate this issue. Is there a specific version of PHP required as well?
