### ISSUE TITLE
mod/questionnaire function has_required() returns an error

### ISSUE THREAD

**Issue by lihidor** [remotelearner/moodle-mod_questionnaire#52]
inside function has_required() the foreach runs on object questionsbysec with [$section], 
but sometimes the value of $section is lower then the value of the first key in questionsbysec  object.
      foreach ($this->questionsbysec[$section] as $question) {
                if ($question->required == 'y') {
                    return true;
                }
      exactly the same problem exists in function survey_render()
thanks Lihi

**Comment by mchurchward** [comment]
Can you provide a situation where $section is ever lower than the first key? That should not be possible.

**Comment by mchurchward** [comment]
Closing as issue has not been responded to in over a year.
