### ISSUE TITLE
Class 'core_external\external_api' not found

### ISSUE THREAD

**Issue by andreasilvestriunitn** [remotelearner/moodle-mod_questionnaire#524]
After updating questionnaire with last version (branch MOODLE_401_STABLE) on Moodle 4.1 brings up an error in the API Documentation page: "Class 'core_external\external_api' not found".
Removing changes committed on file externallib.php as per #502 the error disappear: remove "core_external\" from rows 21 to 25.

**Comment by ptramonti** [comment]
As indicated [here](https://moodledev.io/docs/apis/subsystems/external/functions#:~:text=must%20extend%20the%20external_api%20class%20instead%20of%20%5Ccore_external%5Cexternal_api), you should extend the **external_api** class instead of **\core_external\external_api**.
Thanks

**Comment by aspark21** [comment]
@opitz please review

**Comment by ldgtd** [comment]
Hello, 

We got the same issue on Moodle 4.1.6 w/ the branch MOODLE_401_STABLE. Any update on this ? Thank you

**Comment by jwalits** [comment]
Along with the error on the API documentation page, we are also seeing error in the PHP unit tests
```
1) core\externallib_test::test_all_external_info with data set "mod_questionnaire_submit_questionnaire_response" (stdClass Object (...))
Error: Class 'core_external\external_api' not found

/var/www/site/mod/questionnaire/externallib.php:48
/var/www/site/lib/externallib.php:91
/var/www/site/lib/tests/externallib_test.php:442
/var/www/site/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/site/vendor/phpunit/phpunit/phpunit:97
```

The above commit fixes this up.
