### ISSUE TITLE
number on string error

### ISSUE THREAD

**Issue by SYoung3000** [remotelearner/moodle-mod_questionnaire#538]
We're seeing various users reporting "attempt to define property number on string" when filling out a form.

<img width="1067" alt="Screenshot 2023-12-18 at 15 05 32" src="https://github.com/PoetOS/moodle-mod_questionnaire/assets/77289704/4f8fe210-74e4-4697-a6c0-3946a89a02d5">

It's a numeric question type, so I'm not sure why it's expecting a string (assuming that's what this means) and this has happened since we switched to M4. They are trying to enter a decimal value. Wierdly seems to happen for some users and not others, with no rhyme or reason to this.

**Comment by CPASimUSante** [comment]
The error is described in the [Moodle tracker](https://tracker.moodle.org/browse/CONTRIB-9206) and asked in the [Moodle forum](https://moodle.org/mod/forum/discuss.php?d=452573). A solution is given in the tracker.
