### ISSUE TITLE
"QUESTIONNAIRE_STUDENTVIEWRESPONSES_NEVER" is defined but never used

### ISSUE THREAD

**Issue by papillon326** [remotelearner/moodle-mod_questionnaire#55]
"QUESTIONNAIRE_STUDENTVIEWRESPONSES_NEVER" is defined in "locallib.php". But it's not listed in array $questionnaireresponseviewers. Sometime teacher wants to hide enquete result from students.

**Comment by mchurchward** [comment]
This was removed some time ago. Due to popular demand, it has been re-added. See https://tracker.moodle.org/browse/CONTRIB-5615
