### ISSUE TITLE
Error on response export 4.4

### ISSUE THREAD

**Issue by aguatacuperche** [remotelearner/moodle-mod_questionnaire#567]
Hi. I have an error exporting (downloading) responses. Moodle Version 4.4

During data export you get an error.

View all responses > Summary > Download

`Excepción - Failed opening required '[dirroot]/lib/dataformatlib.php' (include_path='[dirroot]/lib/pear:.:/opt/bitnami/php/lib/php')`

```
Error code: generalexceptionmessage
line 488 of /mod/questionnaire/report.php: Error thrown

```

Thanks.

**Comment by aguatacuperche** [comment]
I have found a solution by commenting out lines 95 and 488 of report.php inside /mod/questionaire/

// $questionnaire->canviewallgroups = has_capability('moodle/site:accessallgroups', $context);

// require_once($CFG->dirroot . '/lib/dataformatlib.php');

**Comment by leonstr** [comment]
This is duplicated by #579 , the latter has PR #587 as a proposed fix fox this.

**Comment by mchurchward** [comment]
This has been fixed in the referenced PR.
