### ISSUE TITLE
Moodle 4.4 questionnaire export answers to csv - Missing  '[dirroot]/lib/dataformatlib.php' 

### ISSUE THREAD

**Issue by mishomvp** [remotelearner/moodle-mod_questionnaire#579]
Hello,

When I try to download the questionnaire answers in csv format.

Exception - Failed opening required '[dirroot]/lib/dataformatlib.php' (include_path='[dirroot]/lib/pear:.:').

It seems that in the new version 4.4 this file is missing.

**Comment by aguatacuperche** [comment]
Hi, I think it is possible that you can provisionally solve the problem by commenting lines 95 and 488 of report.php inside /mod/questionaire/ In my case, it works.

// $questionnaire->canviewallgroups = has_capability('moodle/site:accessallgroups', $context);

// require_once($CFG->dirroot . '/lib/dataformatlib.php');

**Comment by mishomvp** [comment]
Hi :) 
Thanks! It works!

**Comment by rezeau** [comment]
@aguatacuperche I confirm that the hack of commenting out 2 lines does work. But a fix should be provided by @mchurchward

**Comment by leonstr** [comment]
Re removing line 95 of `report.php`, I think this is a separate issue affecting Moodle with PHP >= 8.2 which is fixed in b06947c.

**Comment by thepurpleblob** [comment]
A "me too". Is a fixed version likely soon?

**Comment by mchurchward** [comment]
This has been fixed and merged.

**Comment by cliffbdf** [comment]
Where is the download control? It is missing for me and I have the latest version of Moodle. Did it move in the plugin?
