### ISSUE TITLE
JavaScript error formChild is null on completion page

### ISSUE THREAD

**Issue by leonstr** [remotelearner/moodle-mod_questionnaire#594]
### Steps to reproduce issue

1. Create a course, enrol a teacher and student.
2. As the teacher:
3. Add a Questionnaire to the course.
4. Click _Add questions_ and add a question.
5. As the student click on the Questionnaire on the course page, then click _Answer the questions..._.
6. As the student answer the question and click _Submit questionnaire_.

### Expected results

No errors in browser console.

### Actual results

Error on browser console: _Uncaught TypeError: formChild is null_.

### Environment

This error occurs in Moodle 4.0, 4.1 and 4.2 with mod_questionnaire 2022092202. It occurs with Moodle 4.3.3 and later, and Moodle 4.4 with PR #584 (needed to get the JavaScript to run at all).

**Comment by leonstr** [comment]
PR #595 has a proposed fix for this.

**Comment by mchurchward** [comment]
Fixed in #595
