### ISSUE TITLE
Behat command 'And I add a "Questionnaire" to section "1" and I fill the form with' is deprecated

### ISSUE THREAD

**Issue by lucaboesch** [remotelearner/moodle-mod_questionnaire#597]
Instead of 'And I add a "Questionnaire" to section "1" and I fill the form with' it should be 'And I add a questionnaire activity to course "Course 1" section "1" and I fill the form with:'.

**Comment by leonstr** [comment]
Duplicate of #585?

**Comment by lucaboesch** [comment]
Yeah, right.
Closing.
