### ISSUE TITLE
PHP7 Fatal error: 'break' not in the 'loop' or 'switch

### ISSUE THREAD

**Issue by nitro2010** [remotelearner/moodle-mod_questionnaire#61]
Fatal error: 'break' not in the 'loop' or 'switch' context in /warehouse/lampp/htdocs/moodle/mod/questionnaire/questiontypes/questiontypes.class.php on line 297

**Comment by mchurchward** [comment]
This has been resolved. See https://github.com/remotelearner/moodle-mod_questionnaire/commit/6a9b7ddbf6d90588d85266a4fc87a40aadcdae66
