### ISSUE TITLE
Incorrect Sql Query in function questionnaire_get_recent_mod_activity

### ISSUE THREAD

**Issue by LoveBug** [remotelearner/moodle-mod_questionnaire#62]
This results in database errors in the "Recent Activity" block when a user has completed a questionnaire recently. 

The error is as follows and the sql that causes it is on line 773 of lib.php:

"ERROR: operator does not exist: bigint = character varying
LINE 5: JOIN mdl_user u ON u.id = qr.username
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.

SELECT qr.*,
u.id AS useridagain,u.picture,u.firstname,u.lastname,u.firstnamephonetic,u.lastnamephonetic,u.middlename,u.alternatename,u.imagealt,u.email
FROM mdl_questionnaire_response qr
JOIN mdl_user u ON u.id = qr.username

" 

I assume that u.id is meant to be u.username (or similar) in the join statement, but I am unfamiliar with the code around this area.

**Comment by mchurchward** [comment]
This is also noted in Moodle tracker [CONTRIB-5706](https://tracker.moodle.org/browse/CONTRIB-5706).

**Comment by mchurchward** [comment]
This has been resolved. See https://github.com/remotelearner/moodle-mod_questionnaire/commit/dac895135359f3caaded37793a60a9555575674e
