### ISSUE TITLE
questionnaire submission in postgresql fails when date fields used.

### ISSUE THREAD

**Issue by danmarsden** [remotelearner/moodle-mod_questionnaire#69]
partly related to pull request #68 (same code - slightly different error.)

**Comment by mchurchward** [comment]
Hi Dan.
Can you tell what the incompatibility is in the SQL? The "response" field should be text, and it should be being compared to text, so I'm not sure where Postgres would be having an issue?

**Comment by danmarsden** [comment]
looks like the table structure in the db is different from install.xml - This is pretty historical though - (guessing pre 2.0?) - crazy that it's only showing as a problem now! - I'll try to create a patch to tidy this one up.


   Column    |  Type   |                                  Modifiers                                   
-------------+---------+------------------------------------------------------------------------------
 id          | integer | not null default nextval('mdl_questionnaire_response_date_id_seq'::regclass)
 response_id | integer | not null default 0
 question_id | integer | not null default 0
 response    | date    |

**Comment by danmarsden** [comment]
no patch sorry - but for anyone else having this issue on postgres with a site that has been running questionnaire for a long time here's the query I ran on the db to fix the table structure.

ALTER TABLE mdl_questionnaire_response_date ALTER COLUMN response TYPE text using to_char(response, 'YYYY-MM-DD')

Mike - feel free to close this as "won't fix" - might just be useful for others with old sites.

**Comment by danmarsden** [comment]
looks like it goes back to 1.8 and when we had *.sql scripts for install.

postgresql.sql:

CREATE TABLE prefix_questionnaire_response_date (
    id SERIAL PRIMARY KEY,
    response_id INT NOT NULL default 0,
    question_id INT NOT NULL default 0,
    response DATE
    );

it changed to "text" in 1.9 in the install.xml file but I can't see any upgrade scripts in the 1.9 branch that did the conversion.

**Comment by mchurchward** [comment]
Thanks. I'll add an upgrade step for it anyway. I had to add one for two other "historical" anomalies.
