### ISSUE TITLE
3.1 branch - on creating question no ability to set parent.

### ISSUE THREAD

**Issue by danmarsden** [remotelearner/moodle-mod_questionnaire#70]
in 3.0 branch when creating a new yes/no question you are able to set the parent question.
in 3.1 branch the drop-list to choose the parent question does not show on the creation form. It does show when updating the question though.

using postgres on this machine (not sure if that makes a difference)

**Comment by mchurchward** [comment]
Looks like its true for any question type. Created https://tracker.moodle.org/browse/CONTRIB-6561

**Comment by mchurchward** [comment]
Resolved here - https://github.com/remotelearner/moodle-mod_questionnaire/commit/6c729418f83240bb99d154e61a44812421775b58
