### ISSUE TITLE
3.1 branch editing label question type loses access to edit parent.

### ISSUE THREAD

**Issue by danmarsden** [remotelearner/moodle-mod_questionnaire#71]
when editing an existing label that has previously had a parent question set - the interface gives no ability to change/view the selected parent. The parent still shows on the main questions overview page.

(using postgres if that makes any difference.)

**Comment by mchurchward** [comment]
Hmmm... It looks like the "label" question has been specifically excluded from having a dependency. I'm checking to see if this was intentional, although since it was allowed in 3.0 and prior, it seems like a mistake.

Created https://tracker.moodle.org/browse/CONTRIB-6562

**Comment by mchurchward** [comment]
Resolved here - https://github.com/remotelearner/moodle-mod_questionnaire/commit/d0679ead9294885381a2a2d9add07283e7d7c899
