### ISSUE TITLE
Automated testing bugs

### ISSUE THREAD

**Issue by mrmark** [remotelearner/moodle-mod_questionnaire#72]
Found that questionnaire caused quiz and other features to fail.  This was due to modification of the `$COURSE` global which then cause bad behavior in other parts of Moodle.  Fix is in the attached `behat.patch`.

Found some output during PHPUnit tests.  Fix is in the attached `phpunit.patch`.

[patches.zip](https://github.com/remotelearner/moodle-mod_questionnaire/files/572139/patches.zip)

**Comment by mchurchward** [comment]
Thanks Mark. I'm going to implement that right away. That looks like it could be nasty. As I refactor for 3.2, I'll also check to make sure the "course" property is being used consistently. Right now, it looks like it isn't.

Thanks for the Unit test addition too. I did not know about the "expectOutputString" function.

**Comment by mchurchward** [comment]
Added tracker item https://tracker.moodle.org/browse/CONTRIB-6602

**Comment by mrmark** [comment]
Thanks Mike!
