### ISSUE TITLE
Name "numeric" that is reserved for future use

### ISSUE THREAD

**Issue by mrmark** [remotelearner/moodle-mod_questionnaire#75]
While running https://github.com/sstalle/php7cc - spotted this:

```
File: mod/questionnaire/classes/question/numeric.php
> Line 28: Name "numeric" that is reserved for future use (does not cause an error in PHP 7) used as a class, interface or trait name
    class numeric extends \mod_questionnaire\question\base
    {
    }
```

As the error says, it won't cause an error, but if you want to future proof your code, you will need to rename the class.  Cheers!

**Comment by mchurchward** [comment]
Thanks Mark. I'll get that looked into.

**Comment by mchurchward** [comment]
Created https://tracker.moodle.org/browse/CONTRIB-6896
