### ISSUE TITLE
Rate question results saved incorrectly

### ISSUE THREAD

**Issue by anatolyg7** [remotelearner/moodle-mod_questionnaire#77]
Current master branch saves rate question incorrectly. No matter what value is chosen, after saving answer all results show 1 (leftmost value). Probably this was broken with fix for non-respondents emails

**Comment by mchurchward** [comment]
Thanks for the report. Seems to be in MOODLE_32_STABLE as well. And may be impacting other question types.

**Comment by mchurchward** [comment]
It was this one: https://github.com/remotelearner/moodle-mod_questionnaire/commit/5f42fb557d9f74b4f35b65d6f79a0cd360a1641f#diff-036921bbbfddd3feca9aed2a17b37621

**Comment by mchurchward** [comment]
I added the fix to this commit - https://github.com/remotelearner/moodle-mod_questionnaire/commit/945bdc5d953c46f699fb3106eb238bd8bfb8bee9

I will be doing a full release shortly.
