### ISSUE TITLE
'Rate' response radio buttons appear offset to the left when viewing individual response

### ISSUE THREAD

**Issue by TestValleySchool** [remotelearner/moodle-mod_questionnaire#83]
When using Moodle's base 'clean' theme, or any other bootstrap-based theme, the radio buttons shown when viewing an individual response to a "rate" question are displayed with an offset to the left.

The effect of this is that users viewing an individual response believe that the choice the respondent made was one choice further to the left.

Note that my examples here used named ranks, but this appears to be a problem with standard 1..5 ranks as well.

![questionnaire_template_offset_00](https://cloud.githubusercontent.com/assets/10867163/24502051/0b32333e-1544-11e7-8309-3379f839ad32.png)

In this example, the user chose _Strongly agree_ for the first entry in the table ("Test"), and _Agree_ for the second ("Two").

This does not match the view when answering the same question, where the buttons appear correctly:

![questionnaire_template_offset_01](https://cloud.githubusercontent.com/assets/10867163/24502065/198d964e-1544-11e7-8714-22b4f5c84383.png)

My brief analysis suggests that `/templates/response_rate.mustache` is adding the `radio` class of the div containing the table. https://github.com/remotelearner/moodle-mod_questionnaire/blob/MOODLE_32_STABLE/templates/response_rate.mustache#L60

The `.radio input[type="radio"], .checkbox input[type="checkbox"]` rule in the bootstrap CSS appears to set `float: left; margin-left: -20px;`.

If I remove the `radio` class from the `div` on L60 of `response_rate.mustache`, the radio buttons appear correctly in an individiual response.

I would submit a PR, but I'm not sure if there are other implications to removing this class!

**Comment by mchurchward** [comment]
Can you review https://tracker.moodle.org/browse/CONTRIB-6809? I believe this has already been fixed in the latest code in the MOODLE_32_STABLE branch, and the latest release on moodle.org.

**Comment by mchurchward** [comment]
Thanks for the report. I have created https://tracker.moodle.org/browse/CONTRIB-6815 to deal with this.

**Comment by mchurchward** [comment]
I have fixed the issue and released version 3.2.3 with the fix.
