### ISSUE TITLE
Undefined property : questionnaire::$notifications

### ISSUE THREAD

**Issue by Tazoeur** [remotelearner/moodle-mod_questionnaire#87]
Hi, 

I got a notice for $this->notifications being an undefined property

Here is the path followed after the submission of the questionnaire :
* complete.php (75) : questionnaire->view()
* questionnaire.class.php (292) : questionnaire->submission_notify()
* questionnaire.class.php(1485) : $this->notifications

And de facto, there was no public/private $notifications at the beginning of the class

I Hope this will help,
Guillaume

**Comment by mchurchward** [comment]
The 'notifications' property is a field in the database record. Like most of the properties, it is loaded from the record.
What version of 'questionnaire' are you running? If you have the codebase with that line, it should contain a 'notifications' field in the data table.

**Comment by Tazoeur** [comment]
Hi,

Yeah I think you've already fixed that issue because the questionnaire's version I'm running is 3.1beta (Build - 2016020200)

I should have look at that before posting an issue report...

**Comment by mchurchward** [comment]
No problem. Better safe than sorry. :)
