### ISSUE TITLE
Fix: Reponse export fails to include all data

### ISSUE THREAD

**Issue by mwithheld** [remotelearner/moodle-mod_questionnaire#92]
Hiya RemoteLearner!  Can you please merge pull request #91 https://github.com/remotelearner/moodle-mod_questionnaire/pull/91 ?

**Comment by mchurchward** [comment]
Merged your fix with one to "single.php" as well. Added unit tests. Verified function on MySQL and Postgres as well.
Thanks for the fix!

**Comment by mchurchward** [comment]
Cherry-picked the fixes into MOODLE_33_STABLE, MOODLE_32_STABLE and MOODLE_31_STABLE as well.
