### ISSUE TITLE
Lost data during recover

### ISSUE THREAD

**Issue by salton95** [remotelearner/moodle-mod_questionnaire#93]
Hello! I need help.

I transfered my moodle for a different server with moodle version 3.3 and used a backup file to recover a course in the new site. 

During this process, I lost all the data from my questionnare. It lost the connection it had with the original survey (public).

I tought of updating the data from the public course. Does that make sense? How can I solve this?

Thanks in advance,

Gustavo

**Comment by mchurchward** [comment]
This is not a code issue, so it would be better to take your question to the moodle.org community forums. Probably start in the questionnaire discussion (https://moodle.org/mod/forum/view.php?id=2642). That way, more people will see your issue and hopefully help.
I will close this issue.
