### ISSUE TITLE
Images are not displayed in the responses overview page

### ISSUE THREAD

**Issue by ba-al** [remotelearner/moodle-mod_questionnaire#98]
The issue can be reproduced as follows:
1) Create a Questionnaire with n questions (minimum 2 feedback sections are requiered)
2) Go to Advanced settings, feedback options and edit feedback sections/messages
3) Use the html-editor Image button
- Browse repositories -> URL downloader (insert url to image)
- select this image an select option "make a copy of the file"
- save image
- Image is correctly displayed on the fbsettings page 
(URL in html code: ip/moodle/draftfile.php/5/user/draft/292963019/image.jpg)
4) Answer the question and go to "Individual responses" where images are not displayed.
(URL in html code: ip/moodle/pluginfile.php/30/mod_questionnaire/sectionheading/8/image.jpg)

**Comment by mchurchward** [comment]
Looks like the file area sections for these feedback areas was never added to the 'pluginfile' library function.

**Comment by mchurchward** [comment]
Fixed in master: https://github.com/remotelearner/moodle-mod_questionnaire/commit/680fe8a12202b2a3b283f877af1afe9a2a623876

and MOODLE_33_STABLE: https://github.com/remotelearner/moodle-mod_questionnaire/commit/2c5babb54520b65161a6ed9d4bcd617e037c1d48
